### ISSUE TITLE
Dynamically generate manageStack script

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine#926] opened 2019-07-29 05:32 UTC
As part of the multi-provider project for codeontap we need to update our generation deployment scripts to support multi provider 

This ticket is to replace one of the key scripts in the codeontap deployment process manageStack. This script handles the following steps when running a deployment 

- determining the action to take ( create/update/delete) 
- determining how to perform an update ( replace or update ) 
- recording the outputs from the template run 
etc . 

To support both multi-provider and placements this script could potentially be replaced with a script generated by the template engine which is then executed by the existing manageStack script. 

This would allow for plugins to maintain the contents of the script but still allow us to execute different scripts and processes when required

**Comment by roleyfoley** [comment] 2019-07-29 05:34
@ml019  I think this covers the deploymentPlane script that you semi added into gen3 as part of adding the generatePlan

Who would be best to look at this one? Will need it as part of the new sprint for Azure

**Comment by ml019** [comment] 2019-07-30 01:51
@roleyfoley yep - I kind of figured that we needed the deployment equivalent of genplan.

**Comment by ml019** [comment] 2020-12-10 07:09
Duplicate of #1198

**Closed by ml019** 2020-12-10 07:09 UTC
Labels: enhancement
